name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v4
      
      - name: List files
        run: ls -la

      - name: Show Git status
        run: git status
